version: '3.8'

services:
  oficinahub-keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: oficinahub-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
  oficinahub-keycloak-db:
    image: postgres:15.3
    container_name: oficinahub-keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
  